### ISSUE TITLE
confirmPaymentWithCard please provide setupFutureUsage to save a card during payment

### ISSUE THREAD

**Issue by preflower** [Agaweb/react-native-stripe#10]
i want to save user card during payment, so i need to provide setupFutureUsage  params to let Stripe supported it

**Comment by NicholasBertazzonAga** [comment]
Hey @preflower , isn't the parameter `savePaymentMethod` of the method confirmPaymentWithCard exactly what you want?

**Comment by NicholasBertazzonAga** [comment]
Digged into the Stripe SDK and yes, it is what you want, and it is OffSession by default

**Comment by preflower** [comment]
> Digged into the Stripe SDK and yes, it is what you want, if you set `savePaymentMethod` to true, it will automatically use OffSession by default

thx for u response;
ok, i will use savePaymentMethod params to save a card during payment, but i'm confused that [stripe docs](https://github.com/Agaweb/react-native-stripe/issues/10#issuecomment-808187524) not use savePaymentMethod params to save a card

**Comment by NicholasBertazzonAga** [comment]
@preflower I actually found it on the stripe SDK docs, not those you can find on the website.
From what I understood, it does this
https://github.com/stripe/stripe-android/blob/4e9a222fa027910a914ae9d60a58de6cbe227a95/stripe/src/main/java/com/stripe/android/paymentsheet/model/ConfirmParamsFactory.kt (line 25)

So it should work good, and it's working for me. Maybe in the next update I'll change it to a more recognized OffSession like in the website docs.

**Comment by NicholasBertazzonAga** [comment]
@preflower if you find it to be wrong, feel free to open an issue and I'll look into it asap since this is a pretty important aspect, thanks
