### ISSUE TITLE
CocoaPods could not find compatible versions for pod

### ISSUE THREAD

**Issue by WEETECHDEV** [Agaweb/react-native-stripe#11]
**Describe the bug**
Specs satisfying the `AgawebStripe (from `../node_modules/@agaweb/react-native-stripe`)` dependency were found, but they required a higher minimum deployment target.

**To Reproduce**
1. Go to 'ios folder'
2. Click on 'pod install'
3. See error

![Screenshot 2021-04-17 at 10 21 09 AM](https://user-images.githubusercontent.com/82693973/115102122-a47bf600-9f66-11eb-80a5-c23feefd880c.png)

**Comment by NicholasBertazzon** [comment]
@WEETECHDEV check out the "requirements" section, does your project use ios 11.0 as minimum deployment target?

**Comment by WEETECHDEV** [comment]
![Screenshot 2021-04-19 at 2 56 10 PM](https://user-images.githubusercontent.com/82693973/115213681-6249e480-a11f-11eb-840d-2db1cd97199a.png)
@NicholasBertazzon

**Comment by NicholasBertazzon** [comment]
Podfile not there

**Comment by WEETECHDEV** [comment]
@NicholasBertazzon Yes, Done pod install after clean build folder again I generated podfile and install 


Generating Pods project
Integrating client project
Pod installation complete! There are 48 dependencies from the Podfile and 64 total pods installed.

**Comment by NicholasBertazzonAga** [comment]
Good, in case anyone in the future come out with the same error: check your deployment target in the podfile
