### ISSUE TITLE
confirmCardSetup

### ISSUE THREAD

**Issue by ankushShetty1993** [Agaweb/react-native-stripe#7]
Can we have a callback result for confirmCardSetup function as I need paymentmethodkey for updating by backend

**Comment by NicholasBertazzonAga** [comment]
Hey, it's pretty easy, I'll look into it as soon as I have some free time

**Comment by ankushShetty1993** [comment]
Thank you

**Comment by NicholasBertazzonAga** [comment]
@ankushShetty1993 paymentMethodId is present on the master branch if you want to try it

**Comment by NicholasBertazzonAga** [comment]
Version 0.4.0 published, closing this issue
