### ISSUE TITLE
Allow passing paymentMethod to confirmCardSetup

### ISSUE THREAD

**Issue by aasadalive** [Agaweb/react-native-stripe#9]
I would like to passing `payment_method` to `confirmCardSetup` (I would like to pass `metadata`), here is how it can be done with `tipsi-stripe`:

```ts
const setupIntent = await stripe.confirmSetupIntent({
  clientSecret: clientSetupIntent.client_secret,
  paymentMethod: {
    card,
    metadata: {...},
  },
});
```

The same for `confirmPaymentWithCard`

**Comment by NicholasBertazzonAga** [comment]
Hi @aasadalive , I'll do it when I have some free time, sadly not this week, I can't give you a precise ETA. Pull requests are always there :D

**Comment by aasadalive** [comment]
Sure take your time :+1:!

**Comment by NicholasBertazzonAga** [comment]
Hey @aasadalive , I didn't have much time and there's the official stripe-react-native now, don't expect anything from this lib other than maintenance updates. Sorry.
